### ISSUE TITLE
bug: duplicate tabs

### ISSUE THREAD

**Issue by passioneight** [dachcom-digital/pimcore-seo#28]
# Actual behaviour
After installing & configuring the bundle, the `SEO`-tab contains duplicate tabs:

<img width="897" alt="image" src="https://user-images.githubusercontent.com/57256630/175575103-30c3d374-3ede-444a-9f21-ee81f90e9660.png">

# Expected behaviour
Every tab is displayed exactly once.

# Steps to reproduce.
1. Create Pimcore 10.4.4 instance
2. Require, enable and install bundle
3. Use 2 or more integrators (see below for an example)
4. Create 1 document  and open the `SEO`-tab

```yaml
# Example config

seo:
    meta_data_configuration:
        meta_data_provider:
            auto_detect_documents: true
        meta_data_integrator:
            documents:
                enabled: true
                hide_pimcore_default_seo_panel: true
            enabled_integrator:
                -   integrator_name: title_description
                -   integrator_name: twitter_card
                    integrator_config:
                        twitter_image_thumbnail: 'socialThumb'
```

#### Additional info
I'm aware that the docs state 10.1-10.2 as supported versions, but this bundle [was suggested by the Pimcore-Community](https://github.com/pimcore/pimcore/issues/12399), so, I figured it would still work.
