### ISSUE TITLE
[Title & Description Integrator]: Add noindex option and rename to "General Integrator"

### ISSUE THREAD

**Issue by aarongerig** [dachcom-digital/pimcore-seo#37]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

I would like to introduce a new checkbox field for the "[Title & Description Integrator](https://github.com/dachcom-digital/pimcore-seo/blob/master/docs/MetaData/Integrator/10_TitleDescriptionIntegrator.md)". This checkbox field would allow the user to individually exclude documents/objects from being indexed by Google & Co. By activating it, the SeoBundle would render a `<meta name="robots" content="noindex, nofollow">` meta tag.

Additionally I think it would make sense to rename the Integrator to something like "General Integrator" since it now doesn't only manipulate title and description tags, but more so is there to configure "general" settings relevant to SEO.

**So here are my two questions:**

1. Would you accept such a pull request with the above mentioned changes?
2. Would you also accept the pull request to be merged into V1 in order to release a new version for Pimcore 6?

Looking forward to hear what you think! 🙂

**Comment by aarongerig** [comment]
Any input on this, so I can start with the implementation? Would be very much appreciated – thanks! 🙂

**Comment by solverat** [comment]
@aarongerig That's a good one, thanks! It's already on my to-do list. We're only going to release that for v2, but we would accept a PR for v1 then!

**Comment by solverat** [comment]
@aarongerig I was thinking about how to implement this and I'm wondering if there is an easier way to this.

I came up with this: We're going to extend the "**HTML-Tags**" tab with an additional dropdown "**presets**":

![image](https://user-images.githubusercontent.com/700119/202269465-96a3e8a4-7f54-4e96-a688-825b32088eee.png)

***
Those presets can be configured like this, so it's easy to extend them:

```yaml

  -   integrator_name: html_tag
      integrator_config:
          presets:
              -
                  label: 'Robots No-Index'
                  value: '<meta name="robots" content="noindex, nofollow">'
                  icon_class: 'pimcore_icon_stop'
              -   label: 'Secret Meta-Link'
                  value: '<meta name="secret" content="secret-thing">'
```

***

Furthermore, those preset values cannot be edited:
![image](https://user-images.githubusercontent.com/700119/202270011-e159a965-b42f-4eda-87cc-f2cb4bc77609.png)

***

Also, to assert safety here, it's possible to disable the "Add HTML Tag-Field" (and also the warning) by adding the `presets_only_mode` flag:

```yaml

-   integrator_name: html_tag
    integrator_config:
        presets_only_mode: true
        presets:
            -
                label: 'Robots No-Index'
                value: '<meta name="robots" content="noindex, nofollow">'
                icon_class: 'pimcore_icon_stop'
```

***

Which then looks like this:
![image](https://user-images.githubusercontent.com/700119/202270287-cb55a620-af1f-4ef4-949e-52c57a952fe1.png)

![image](https://user-images.githubusercontent.com/700119/202278570-51d1ed18-e323-4704-b0d7-09649fca2281.png)

***

What do you think?
